### ISSUE TITLE
`NETVISOR_DISABLE_REGISTRATION` environment variable is not being read

### ISSUE THREAD

**Issue by sinsky** [scanopy/scanopy#133]
**Describe the bug**
The `NETVISOR_DISABLE_REGISTRATION` environment variable is documented as supported but is not actually being read by the configuration system. The CLI argument always overrides the environment variable, even when not explicitly provided.

**To Reproduce**
1. Download the docker compose file: `wget https://github.com/mayanayza/netvisor/raw/refs/heads/main/docker-compose.yml`
2. Add `NETVISOR_DISABLE_REGISTRATION: true` to the server's environment variables in the docker-compose.yml file
3. Run `docker compose up -d`
4. Check the configuration via API: `curl http://localhost:60072/api/config | jq ".data.disable_registration"`
5. Observe that the value is `false` despite the environment variable being set to `true`

**Expected behavior**
When `NETVISOR_DISABLE_REGISTRATION=true` is set and no CLI argument is provided, registration should be disabled. The configuration priority should be: Defaults → Environment Variables → CLI Arguments (highest priority).

**Environment:**
- Host: bare metal (Docker)
- OS: Debian 13
- Browser: N/A (server-side issue)
- Version: v0.9.1

**Additional context**
The issue is in `backend/src/server/config.rs` in the `ServerConfig::load()` function. 

**Code reference:** 
https://github.com/mayanayza/netvisor/blob/612d6c7e80c0c3008d98731f67feb5f923c91ef2/backend/src/server/config.rs#L144

Unlike other configuration fields that use conditional merging, `disable_registration` uses unconditional merging, causing the CLI argument (which defaults to `false` when not provided) to always override the environment variable.

**Documentation inconsistency:**
The README also shows an incorrect default value for this parameter:
https://github.com/mayanayza/netvisor/blob/612d6c7e80c0c3008d98731f67feb5f923c91ef2/README.md?plain=1#L634

**Before submitting**
[x] I have reviewed [Troubleshooting](https://github.com/mayanayza/netvisor#troubleshooting) in the readme

**Comment by bas0N** [comment]
@mayanayza I can take this issue and prepare a PR for it. Could you please assign it to me?

**Comment by mayanayza** [comment]
This should be fixed in v0.12.8 (currently pre-release, not yet latest)

**Comment by kavemang** [comment]
@mayanayza with this set to true (I confirmed it it set inside the container) the registration buttons and fields still show, do they throw an error if someone proceeds through filling out the fields?
