### ISSUE TITLE
Docker Container being discovered multiple times on Proxmox

### ISSUE THREAD

**Issue by abhrabasak** [scanopy/scanopy#336]
**Describe the bug**
I have 4 Docker LXCs spread across 2 Proxmox nodes in a cluster. Node 1 hosts LXCs for {Apps, Database, Networking}, and Node 2 hosts LXC for {Media}. I host the Scanopy server and default daemon on Docker in the Networking LXC, and have deployed 3 additional Docker daemons in the Apps, Database, Media LXCs. All Proxmox hosts and Docker LXCs are on the same subnet (192.168.68.0/22)

<img width="234" height="460" alt="Image" src="https://github.com/user-attachments/assets/f91c9c82-0730-460d-b34d-39980f17be0f" />

Each daemon exposes Self-Reporting, Network Discovery and Docker Discovery capabilities. On running the discovery after the initial discovery, it "re-discovers" the Docker LXCs and show them as empty.

<img width="3314" height="1924" alt="Image" src="https://github.com/user-attachments/assets/11d3886d-628e-4670-9e11-04009ec3396f" />

<img width="1657" height="554" alt="Image" src="https://github.com/user-attachments/assets/ebe02b03-aaf0-4ef0-9770-ce37bd0df8aa" />

These hosts were already discovered and registered in the initial run.

<img width="1634" height="810" alt="Image" src="https://github.com/user-attachments/assets/a2c496ce-174f-4446-902b-d370785d89c3" />

Also, when I look into the named LXCs discovered in the initial run, the Docker network bridges and interfaces are all duplicated. And so are the nodes for those Docker containers in the topology.

<img width="371" height="707" alt="Image" src="https://github.com/user-attachments/assets/08e52ffc-87be-4893-8426-50f86584f324" />

<img width="364" height="675" alt="Image" src="https://github.com/user-attachments/assets/d78a6cb7-b91c-4931-9cfc-3af36d255cc4" />

<img width="971" height="487" alt="Image" src="https://github.com/user-attachments/assets/da2945bb-6809-4fca-b96b-d47be21d4ad9" />

**Am I using this in an incorrect way?**

**To Reproduce**
1. Setup Scanopy server and daemon on container in Docker LXC on Proxmox
2. Setup Scanopy daemon on additional container in Docker LXC on Proxmox, in the same subnet
3. Run initial discovery
4. Rerun Network and Docker discovery from the Scheduled tab

**Expected behavior**
I would like to be able to re-run the discovery multiple times, and still expect the system to conflate re-discovered nodes (hosts and containers) with existing ones.
The conflation logic could possibly be based on MAC address, and/or interface name.

**Screenshots**
Added above

**Environment:** 
 - Scanopy server & daemon version (can be found in logs)
 - Host: [Docker container on Proxmox LXC]
 - OS: [Debian host, Browsing on Windows/MacOS]
 - Browser [firefox]

**Additional context**

**Before submitting**
[x] I have reviewed [Troubleshooting](https://github.com/scanopy/scanopy#troubleshooting) in the readme

**Comment by mayanayza** [comment]
Thank you for this detailed report! There is logic to automatically merge discovered data that belongs to the same host, but this pointed out a few gaps in that specifically related to docker discovery, as you were encountering. This should now be fixed in v0.12.5.

**Comment by abhrabasak** [comment]
I upgraded the version to v0.12.5 on the server and all daemons.
Some of the interfaces and services in the docker host are still getting duplicated, on running the Docker Discovery on that host.

**Comment by mayanayza** [comment]
I added a section on how host deduplication to the docs: https://scanopy.net/docs/discovery/#host-deduplication

Can you review the deduplication methodology and lmk if you see any gaps present that could account for the issues you're still seeing? There may need to be more done to account for proxmox node clusters / multiple docker daemons on one proxmox host, but ultimately determining this will come down to reconciling your networking configuration with the deduplication methodology.

The main change I made in v0.12.5 is that docker discovery will now also use mac ID / ip + subnet to deduplicate host entries, whereas before it relied solely on the provenance of the daemon running discovery to deduplicate. The setup you have is a bit more complex than mine, and I suspect that this wasn't enough to account for the way you have clustering configured + how network interfaces may be implemented/shared in your proxmox setup.

**Comment by abhrabasak** [comment]
I investigated this a bit more, and it looks like the interfaces are not the ones getting duplicated, it is the services. And the duplication happens only on certain services. I have the following hypothesis:

<img width="462" height="447" alt="Image" src="https://github.com/user-attachments/assets/bf1a5a66-2bbc-4ff6-bacd-e84dab07b282" />
<img width="478" height="481" alt="Image" src="https://github.com/user-attachments/assets/1d0664ea-dd87-4887-8e0b-f2f085d309ea" />

In this diagram, {`portainer-agent`, `traefik`, `jellyfin`} were originally detected as generic Docker containers (with Docker icon), along with `dozzle-agent` (Generic) and `scanopy-daemon` (recognized).
I went on to create matched services for {`portainer-agent`, `traefik`, `jellyfin`} to get the correct icons, and used the "Transfer ports" mechanism to move the associated interfaces from the services with Docker icons. Then I deleted the original Generic services. 

On the next discovery run, these manually created services are the only ones that get duplicated, and get added at the end.
These "new" services with Docker icons have the exact same set of interfaces/ports that are already in the manually created "specific" services (but maybe in a different order).

Take the example of `jellyfin`.

<img width="2332" height="1034" alt="Image" src="https://github.com/user-attachments/assets/b676a858-d3c1-4ff2-b06e-0be51e3d1e57" />
<img width="2322" height="1040" alt="Image" src="https://github.com/user-attachments/assets/39b5fdbb-a7be-404b-9c56-3fdec80bc12e" />

I have reproduced this behavior consistently in all my 4 Docker LXCs. I hope this helps determine a richer de-duplication mechanism for the services.

**Comment by abhrabasak** [comment]
I have another hypothesis - This is happening whenever I transfer ports from an auto-discovered Generic service to a manually added specific service. This is not a problem just in Docker hosts, but all kinds of hosts. For example, I transferred unclaimed ports into IoT service for a smart plug, and the ports were duplicated in the service tab under unclaimed ports again.

<img width="2340" height="1084" alt="Image" src="https://github.com/user-attachments/assets/3db9a4a0-ebb5-4cfa-814d-8ebbb229dcd0" />
Example, I moved unclaimed ports on my Amazon Echo to a recognized Amazon Echo service binding, and the interfaces/ports got rediscovered

**Comment by mayanayza** [comment]
This should be fixed in pre-release v0.12.8 - please give it a shot with that specific tag (it isn't pushed to latest yet).

v0.12.8 implements better validation around service deduplication taking into account the port transfer feature, among other fixes.

Note that if you haven't yet upgraded to v0.12.7+, you may run into a database constraint issue upon doing so; based on what you're describing, duplicate ports have been created, and v0.12.7 introduces better database validation around things like port uniqueness per host. 

If you do encounter this, please run this cleanup script which will delete duplicate ports (and will also take care of other data validation requirements). The script is available at https://github.com/scanopy/scanopy/blob/main/backend/scripts/fix_migration_data.sql. 

I'd highly recommend using -v DRY_RUN=true for the first run to confirm it will execute successfully. If any issues, please let me know!

**Comment by abhrabasak** [comment]
This is still a problem in v0.12.10.
Instead of running the script, I manually deleted all interfaces, ports and services on all the affected hosts, and re-ran discovery.
The problem has been re-referenced in #409
